#!/bin/bash
# chkconfig: 345 75 25
# description: XQBase Metric Collector Service

PID_FILE=/var/run/metric-collector.pid
case "$1" in
        start)
                java -jar /usr/local/xqbase-metric/lib/metric-collector.jar &
                echo $! > $PID_FILE
                ;;
        stop)
                read pid < $PID_FILE
                kill $pid
                rm $PID_FILE
                ;;
esac