var DASHBOARD_HEIGHT = 600;
var DASHBOARD_LENGTH = 100;
var DASHBOARD_SERIES = 10;
var DASHBOARD_TAGS_TOP = false;
var DASHBOARD_CHART_TYPE = "line";
var DASHBOARD_MARKER = false;
var DASHBOARD_API = "api/";